env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  keyword-spacing:
    - error
  key-spacing:
    - error
  array-bracket-spacing:
    - error
    - never
  block-spacing:
    - error
    - always
  arrow-spacing:
    - error
  space-before-blocks:
    - error
  space-infix-ops:
    - error
  no-whitespace-before-property:
    - error
  space-in-parens:
    - error
    - never
  object-curly-spacing:
    - error
    - always
  no-warning-comments:
    - error
  no-var:
    - error
